DA_TOTNGHIEP/Areas/Admin/Controllers/UserStatisticsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_TOTNGHIEP.Data;
using DA_TOTNGHIEP.Models;
using static DA_TOTNGHIEP.Helper;
using DA_TOTNGHIEP.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace DA_TOTNGHIEP.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "Admin,Sale")]
    public class UserStatisticsController : Controller
    {       
        private readonly DA_TOTNGHIEP2Context _context;
        public UserStatisticsController(DA_TOTNGHIEP2Context context)
        {
            _context = context;
        }

        public IActionResult Index(string sortUserAscending = "", string sortUserDescending = "")
        {
            ViewBag.CountStock = _context.Products.Sum(p => p.Stock).ToString("##,#0");
            ViewBag.CountProduct = (from ok in _context.Products select ok.Id).Count().ToString("##,#0");
            ViewBag.TongDoanhThu = _context.Invoices.Where(inv => inv.StatusId == 4).Sum(inv => inv.Total).ToString("##,#0 ₫");
            ViewBag.SoLuongDaBan = _context.InvoiceDetails.Where(inv => inv.MomoConfirm != "Giao dịch Momo bị huỷ" && inv.Invoice.StatusId == 4).Sum(inv => inv.Quantity).ToString("##,#0");

            var db_DOANTOTNGHIEPContext = Tuple.Create<IEnumerable<Invoices>, IEnumerable<InvoiceDetails>>(_context.Invoices.Include(i => i.Account).Include(i => i.ProductItems).Include(i => i.User).Include(i => i.InvoiceDetails).ToList(), _context.InvoiceDetails.Include(i => i.Invoice).Include(i => i.Product).Include(i => i.Product.ImageProductss).ToList());

            
            //Sắp xếp SPBC theo thứ tự tăng - giảm
            ViewData["UserAscending"] = string.IsNullOrEmpty(sortUserAscending) ? "ascending" : "";
            switch (sortUserAscending)
            {
                case "ascending":

                    break;
            }
            ViewData["UserDescending"] = string.IsNullOrEmpty(sortUserDescending) ? "descending" : "";
            switch (sortUserDescending)
            {
                case "descending":

                    break;
            }

            return View(db_DOANTOTNGHIEPContext);
        }
    }
}

DA_TOTNGHIEP/Areas/Admin/Views/UserStatistics/Index.cshtml
@model Tuple<IEnumerable<DA_TOTNGHIEP.Models.Invoices>, IEnumerable<DA_TOTNGHIEP.Models.InvoiceDetails>>

@{
    ViewData["Title"] = "Thống kê người dùng";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
<h3>Thống kê người dùng</h3>
<div class="card mt-2">
    <div class="card-content">
        <div class="card-body">
            @*<form asp-controller="ProductStatistics" asp-action="Index" method="get" style="display:inline;margin-left:12rem;">
                <div>
                    <fieldset class="form-group d-inline-flex pr-2">
                        <div>
                            <span style=" font-weight: 700;">Thông tin:</span>
                            <div>
                                <input type="text" name="SearchString" placeholder="Nhập SKU, Tên SP..." class="input-css" style="border: 1px solid #dce7f1;border-radius: .25rem;padding: 6px;" />
                            </div>
                        </div>
                    </fieldset>
                </div>
                <button type="submit" class="btn btn-danger">Tìm kiếm <i class="fas fa-search"></i></button>
            </form>*@
            <div style="display:flex">
                <div style="margin-top: 1rem;margin-bottom:1rem;margin-left:1rem">
                    <h4 style=" font-weight: 700;">Sắp xếp người dùng đã mua nhiều nhất:</h4>
                    <h6 style="color: #d70018;">(Khách hàng VIP là khách hàng có tổng số tiền đã mua trên 200.000.000 ₫)</h6>
                    <div>
                        @if (@ViewData["UserAscending"] != "")
                        {
                            <button class="sort-product-ascending" style=" background: #f0f0f0;">
                                <a asp-controller="UserStatistics" asp-action="Index" asp-route-sortUserAscending="@ViewData["UserAscending"]" style="color: #000;">Thấp - Cao <i class="fas fa-sort-amount-up"></i></a>
                            </button>
                        }
                        else if (@ViewData["UserAscending"] == "")
                        {
                            <button class="sort-product-ascending" style=" background: #f0f0f0;">
                                <a asp-controller="UserStatistics" asp-action="Index" asp-route-sortUserAscending="@ViewData["UserAscending"]" style="color:blue">Thấp - Cao <i class="fas fa-sort-amount-up"></i></a>
                            </button>
                        }
                        @if (@ViewData["UserDescending"] != "")
                        {
                            <button class="sort-product-ascending" style=" background: #f0f0f0;">
                                <a asp-controller="UserStatistics" asp-action="Index" asp-route-sortUserDescending="@ViewData["UserDescending"]" style="color: #000;">Cao - Thấp <i class="fas fa-sort-amount-down"></i></a>
                            </button>
                        }
                        else if (@ViewData["UserDescending"] == "")
                        {
                            <button class="sort-product-ascending" style=" background: #f0f0f0;">
                                <a asp-controller="UserStatistics" asp-action="Index" asp-route-sortUserDescending="@ViewData["UserDescending"]" style="color:blue">Cao - Thấp <i class="fas fa-sort-amount-down"></i></a>
                            </button>
                        }
                    </div>
                </div>
            </div>

            <div class="scrollmenu" style="overflow: scroll; white-space: nowrap; height: 500px;">
                <div class="table-responsive" style="overflow-x:unset !important; margin-bottom:2rem">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>
                                    STT
                                </th>
                                <th style="width: 30%;">
                                    Email người dùng
                                </th>
                                <th>
                                    Tổng số tiền đã mua
                                </th>
                                <th>
                                    Tổng SL sản phẩm đã mua
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (@ViewData["UserAscending"] != "" && @ViewData["UserDescending"] != "")
                            {
                                int stt = 1;
                                @foreach (var itemproduct in Model.Item2.GroupBy(i => i.Invoice.UserId).Select(p => new
                                {
                                    Id = p.Key,
                                    Email = p.Select(o => o.Invoice.User.Email).FirstOrDefault(),
                                    Quantity = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.Quantity),
                                    Money = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.UnitPrice * o.Quantity),
                                }).OrderBy(i => i.Id).ToList())
                                {
                                    <tr>
                                        <td>
                                            @(stt++)
                                        </td>
                                        @if(itemproduct.Money >= 200000000) 
                                        { 
                                            <td>
                                                @itemproduct.Email <img src="~/assetsUser/img/vip.png" style="height: 28px; width: 28px;" />
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                @itemproduct.Email
                                            </td>
                                        }
                                        <td>
                                            @itemproduct.Money.ToString("##,#0 ₫")
                                        </td>
                                        <td>
                                            @itemproduct.Quantity
                                        </td>
                                    </tr>
                                }
                            }
                            else if (@ViewData["UserAscending"] == "")
                            {
                                int stt = 1;
                                @foreach (var itemproduct in Model.Item2.GroupBy(i => i.Invoice.UserId).Select(p => new
                                {
                                    Id = p.Key,
                                    Email = p.Select(o => o.Invoice.User.Email).FirstOrDefault(),
                                    Quantity = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.Quantity),
                                    Money = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.UnitPrice * o.Quantity),
                                }).OrderBy(i => i.Money).ToList())
                                {
                                    <tr>
                                        <td>
                                            @(stt++)
                                        </td>
                                        @if(itemproduct.Money >= 200000000) 
                                        { 
                                            <td>
                                                @itemproduct.Email <img src="~/assetsUser/img/vip.png" style="height: 28px; width: 28px;"/>
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                @itemproduct.Email
                                            </td>
                                        }
                                        <td style="font-weight:bold;color:#000">
                                            @itemproduct.Money.ToString("##,#0 ₫")
                                        </td>
                                        <td>
                                            @itemproduct.Quantity
                                        </td>
                                    </tr>
                                }
                            }
                            else if (@ViewData["UserDescending"] == "")
                            {
                                int stt = 1;
                                @foreach (var itemproduct in Model.Item2.GroupBy(i => i.Invoice.UserId).Select(p => new
                                {
                                    Id = p.Key,
                                    Email = p.Select(o => o.Invoice.User.Email).FirstOrDefault(),
                                    Quantity = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.Quantity),
                                    Money = p.Where(o => o.Invoice.StatusId == 4 && o.MomoConfirm != "Giao dịch Momo bị huỷ").Sum(o => o.UnitPrice * o.Quantity),
                                }).OrderByDescending(i => i.Money).ToList())
                                {
                                    <tr>
                                        <td>
                                            @(stt++)
                                        </td>
                                        @if(itemproduct.Money >= 200000000) 
                                        { 
                                            <td>
                                                @itemproduct.Email <img src="~/assetsUser/img/vip.png" style="height: 28px; width: 28px;" />
                                            </td>
                                        }
                                        else
                                        {
                                            <td>
                                                @itemproduct.Email
                                            </td>
                                        }
                                        <td style="font-weight:bold;color:#000">
                                            @itemproduct.Money.ToString("##,#0 ₫")
                                        </td>
                                        <td>
                                            @itemproduct.Quantity
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>