DA_TOTNGHIEP/Areas/Admin/Controllers/ImportWarehousesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_TOTNGHIEP.Models;
using static DA_TOTNGHIEP.Helper;
using DA_TOTNGHIEP;
using DA_TOTNGHIEP.Data;
using Microsoft.AspNetCore.Authorization;

namespace DA_TOTNGHIEP.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Sale")]

    public class ImportWarehousesController : Controller
    {
        private readonly DA_TOTNGHIEP2Context _context;

        public ImportWarehousesController(DA_TOTNGHIEP2Context context)
        {
            _context = context;
        }

        // GET: Admin/ImportWarehouses
        public IActionResult Index(DateTime fromDate, DateTime toDate, string SearchString = "")
        {
            ViewBag.CountStock = _context.Products.Sum(p => p.Stock).ToString("##,#0");
            ViewBag.CountProduct = (from ok in _context.Products select ok.Id).Count().ToString("##,#0");
            ViewBag.TongDoanhThu = _context.Invoices.Where(inv => inv.StatusId == 4).Sum(inv => inv.Total).ToString("##,#0 ₫");
            ViewBag.SoLuongDaBan = _context.InvoiceDetails.Where(inv => inv.MomoConfirm != "Giao dịch Momo bị huỷ" && inv.Invoice.StatusId == 4).Sum(inv => inv.Quantity).ToString("##,#0");

            if (SearchString != "" && SearchString != null)
            {
                if (fromDate.ToString("dd/MM/yyyy") != "01/01/0001" && toDate.ToString("dd/MM/yyyy") != "01/01/0001")
                {
                    return View(_context.ImportWarehouse.Include(i => i.Warehouse).Where(i => i.CreatedAt.Date >= fromDate && i.CreatedAt.Date <= toDate && (i.Code.Contains(SearchString) || i.Supplier.Contains(SearchString) ||
                                                                                i.Shipment.Contains(SearchString) || i.ProductName.Contains(SearchString))).ToList());
                }
                else 
                { 
                    return View(_context.ImportWarehouse.Include(i => i.Warehouse).Where(i => i.Code.Contains(SearchString) || i.Supplier.Contains(SearchString) ||
                                                                                i.Shipment.Contains(SearchString) || i.ProductName.Contains(SearchString)).ToList());
                }
            }

            if (fromDate.ToString("dd/MM/yyyy") != "01/01/0001" && toDate.ToString("dd/MM/yyyy") != "01/01/0001")
            {
                return View(_context.ImportWarehouse.Include(i => i.Warehouse).Where(i => i.CreatedAt.Date >= fromDate && i.CreatedAt.Date <= toDate).ToList());
            }
            else if (fromDate.ToString("dd/MM/yyyy") == "01/01/0001" && toDate.ToString("dd/MM/yyyy") == "01/01/0001")
            {
                return View(_context.ImportWarehouse.Include(i => i.Warehouse).ToList());
            }

            var db_DOANTOTNGHIEPContext = _context.ImportWarehouse.Include(i => i.Warehouse);
            return View(db_DOANTOTNGHIEPContext);
        }

        // GET: Admin/ImportWarehouses/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var importWarehouse = await _context.ImportWarehouse
                .Include(i => i.Warehouse)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (importWarehouse == null)
            {
                return NotFound();
            }

            return View(importWarehouse);
        }

        // GET: Admin/ImportWarehouses/Create
        [NoDirectAccess]
        public async Task<IActionResult> Create(int id = 0)
        {
            ViewData["ProductId"] = new SelectList(_context.Products, "Id", "Name");
            ViewData["WarehouseId"] = new SelectList(_context.Warehouse, "Id", "Name");
            if (id == 0)
                return View(new ImportWarehouse());

            else
            {
                var importWarehouse = await _context.ImportWarehouse.FindAsync(id);
                if (importWarehouse == null)
                {
                    return NotFound();
                }

                return View(importWarehouse);
            }
        }

        // POST: Admin/ImportWarehouses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Id,Code,SupplierCode,Supplier,ProductName,Stock,WarehouseId,ProductId,Shipment,CreatedAt")] ImportWarehouse importWarehouse)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    _context.Add(importWarehouse);
                    ViewData["WarehouseId"] = new SelectList(_context.Warehouse, "Id", "Name", importWarehouse.WarehouseId);
                    await _context.SaveChangesAsync();
                }
                ViewData["WarehouseId"] = new SelectList(_context.Warehouse, "Id", "Name", importWarehouse.WarehouseId);
                return RedirectToAction("Index");
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", importWarehouse) });
        }

        // GET: Admin/ImportWarehouses/Edit/5
        [NoDirectAccess]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == 0)
                return View(new ImportWarehouse());

            else
            {
                var importWarehouse = await _context.ImportWarehouse.FindAsync(id);
                if (importWarehouse == null)
                {
                    return NotFound();
                }
                ViewData["WarehouseId"] = new SelectList(_context.Warehouse, "Id", "Name", importWarehouse.WarehouseId);
                return View(importWarehouse);
            }
        }

        // POST: Admin/ImportWarehouses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Code,SupplierCode,Supplier,ProductName,Stock,WarehouseId,ProductId,Shipment,CreatedAt")] ImportWarehouse importWarehouse)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(importWarehouse);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ImportWarehouseExists(importWarehouse.Id))
                    { return NotFound(); }
                    else
                    { throw; }
                }
            ViewData["WarehouseId"] = new SelectList(_context.Warehouse, "Id", "Name", importWarehouse.WarehouseId);
                return RedirectToAction("Index");
            }   
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", importWarehouse) });
        }

       
        // POST: Admin/ImportWarehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var importWarehouse = await _context.ImportWarehouse.FindAsync(id);
            _context.ImportWarehouse.Remove(importWarehouse);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool ImportWarehouseExists(int id)
        {
            return _context.ImportWarehouse.Any(e => e.Id == id);
        }
    }
}

DA_TOTNGHIEP/Areas/Admin/Views/ImportWarehouses/Create.cshtml
@model DA_TOTNGHIEP.Models.ImportWarehouse

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<h3>Tạo phiếu nhập kho</h3>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierCode" class="control-label"></label>
                <input asp-for="SupplierCode" class="form-control" />
                <span asp-validation-for="SupplierCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <input asp-for="Supplier" class="form-control" />
                <span asp-validation-for="Supplier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shipment" class="control-label"></label>
                <input asp-for="Shipment" class="form-control" />
                <span asp-validation-for="Shipment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="WarehouseId" class="control-label"></label>
                <select asp-for="WarehouseId" class="form-control" asp-items="ViewBag.WarehouseId"></select>
            </div>*@
            @*<div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class="form-control" asp-items="ViewBag.ProductId"></select>
            </div>*@
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

DA_TOTNGHIEP/Areas/Admin/Views/ImportWarehouses/Edit.cshtml
@model DA_TOTNGHIEP.Models.ImportWarehouse

@{
    ViewData["Title"] = "Create";
    Layout = null;
}

<h3>Sửa phiếu nhập kho</h3>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Code" class="control-label"></label>
                <input asp-for="Code" class="form-control" />
                <span asp-validation-for="Code" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierCode" class="control-label"></label>
                <input asp-for="SupplierCode" class="form-control" />
                <span asp-validation-for="SupplierCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Supplier" class="control-label"></label>
                <input asp-for="Supplier" class="form-control" />
                <span asp-validation-for="Supplier" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ProductName" class="control-label"></label>
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Shipment" class="control-label"></label>
                <input asp-for="Shipment" class="form-control" />
                <span asp-validation-for="Shipment" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Stock" class="control-label"></label>
                <input asp-for="Stock" class="form-control" />
                <span asp-validation-for="Stock" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="WarehouseId" class="control-label"></label>
                <input asp-for="WarehouseId" class="form-control" />
                <span asp-validation-for="WarehouseId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Sửa" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

DA_TOTNGHIEP/Areas/Admin/Views/ImportWarehouses/Index.cshtml
@model IEnumerable<DA_TOTNGHIEP.Models.ImportWarehouse>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DA_TOTNGHIEP/Areas/Admin/Views/ImportWarehouses/_ViewAll.cshtml
@model IEnumerable<DA_TOTNGHIEP.Models.ImportWarehouse>

@{
    ViewData["Title"] = "ViewAll";
}

<h3>Danh sách phiếu nhập kho</h3>
<div class="card mt-2">
    <div class="card-content">
        <div class="card-body">
            <a onclick="showInPopup('@Url.Action("Create","ImportWarehouses",null,Context.Request.Scheme)','Tạo loại sản phẩm')" class="btn btn-primary"><i class='bx bx-plus-circle ml-1'></i><h5 style="display:inline;color:white"> Tạo phiếu nhập kho</h5></a>
            <form asp-controller="ImportWarehouses" asp-action="Index" method="get" style="display:inline;margin-left:12rem;">
                <div style="display:flex">
                    <div style="margin-top:1rem">
                        <div>
                            <div>
                                <span style=" font-weight: 700;">Thông tin:</span><input type="text" name="SearchString" placeholder="Nhập mã, tên..." class="input-css" style="border: 1px solid #dce7f1;border-radius: .25rem;padding: 6px;" />
                            </div>
                        </div>
                    </div>
                    <div style="margin-top:1rem;margin-left:1rem">
                        <span style=" font-weight: 700;">Từ ngày:</span> <input type="date" id="birthdaytime" name="fromDate" style="
                                                                    border: 1px solid;
                                                                    border-radius: 7px;
                                                                    padding: 8px;
                                                                ">
                        <span style=" font-weight: 700;">đến ngày:</span> <input type="date" id="birthdaytime" name="toDate" style="
                                    border: 1px solid;
                                    border-radius: 7px;
                                    padding: 8px;
                                ">
                    </div>
                </div>
                <button type="submit" class="btn btn-danger" style="margin-top:1rem">Tìm kiếm <i class="fas fa-search"></i></button>
            </form>
            <div class="scrollmenu" style="overflow: auto; white-space: nowrap;height:700px">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead>
                            <tr>
                                <th>
                                    STT
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Code)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.SupplierCode)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Supplier)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.ProductName)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Shipment)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Stock)
                                </th>
                                @*<th>
            @Html.DisplayNameFor(model => model.WarehouseId)
        </th>*@
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedAt)
                                </th>
                                @*<th>
            @Html.DisplayNameFor(model => model.Product)
        </th>*@
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count() != 0)
                            {
                                int stt = 1;
                                @foreach (var item in Model)
                                {
                            <tr>
                                <td>
                                    @(stt++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Code)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.SupplierCode)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Supplier)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.ProductName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Shipment)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Stock)
                                </td>
                                @*<td>
            @Html.DisplayFor(modelItem => item.WarehouseId)
        </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.CreatedAt)
                                </td>
                                <td>
                                    <div>
                                        <button style="border: none; background: none;" onclick="showInPopup('@Url.Action("Edit","ImportWarehouses",new {id=item.Id})','Update')"><i title="Sửa" class="fas fa-edit" style="font-size: 23px; color: #415ebf "></i></button>
                                        <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                            <button type="submit" title="Xóa" style="border: none; background: none;"><i class="fas fa-trash-alt" style="font-size:23px;color:crimson"></i></button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                                }

                            }
                            else
                            {
                                <tr>
                                    <td colspan="3" style="color:crimson">Không có dữ liệu ! <i class="far fa-frown"></i>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>