DA_TOTNGHIEP/Areas/Admin/Controllers/StatiscalInvoicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_TOTNGHIEP.Data;
using DA_TOTNGHIEP.Models;
using static DA_TOTNGHIEP.Helper;
using DA_TOTNGHIEP.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace DA_TOTNGHIEP.Areas.Admin.Controllers
{

    [Area("Admin")]
    [Authorize(Roles = "Admin,Sale")]
    public class StatiscalInvoicesController : Controller
    {       
        private readonly DA_TOTNGHIEP2Context _context;
        public StatiscalInvoicesController(DA_TOTNGHIEP2Context context)
        {
            _context = context;
        }

        public IActionResult Index(DateTime fromDate,DateTime toDate)
        {
            ViewBag.CountStock = _context.Products.Sum(p => p.Stock).ToString("##,#0");
            ViewBag.CountProduct = (from ok in _context.Products select ok.Id).Count().ToString("##,#0");
            ViewBag.TongDoanhThu = _context.Invoices.Where(inv => inv.StatusId == 4).Sum(inv => inv.Total).ToString("##,#0 ₫");
            ViewBag.SoLuongDaBan = _context.InvoiceDetails.Where(inv => inv.MomoConfirm != "Giao dịch Momo bị huỷ" && inv.Invoice.StatusId == 4).Sum(inv => inv.Quantity).ToString("##,#0");

            var countInvoice = _context.Invoices.Where( x => x.StatusId != 3 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Count();
            ViewBag.countInvoices = countInvoice;
            var countUnApprove = _context.Invoices.Where(x => x.StatusId == 0 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Count();
            ViewBag.countUnApprove = countUnApprove;
            var countShip = _context.Invoices.Where(x => x.StatusId == 1 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Count();
            ViewBag.countShip = countShip;
            var countCancel = _context.Invoices.Where(x => x.StatusId == 2 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Count();
            ViewBag.countCancel = countCancel;
            var countApproved = _context.Invoices.Where(x => x.StatusId == 4 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Count();
            ViewBag.countApproved = countApproved;
            var doanhThu = _context.Invoices.Where(x => x.StatusId == 4 && x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate).Select(x => x.Total).Sum();
            ViewBag.doanhThu = doanhThu;

            /*var today = DateTime.Today;
            var total = _context.Invoices.Where(x => x.IssuedDate.Date >= fromDate && x.IssuedDate.Date <= toDate && x.StatusId == 4)
                .Select(x => x.Total).Sum().ToString("##,# ₫");
            ViewBag.total = total;*/
            return View();
        }
    }
}

DA_TOTNGHIEP/Areas/Admin/Views/StatiscalInvoices/Index.cshtml
@model DA_TOTNGHIEP.Models.Invoices
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}
@{
    int doanhThu = ViewBag.doanhthu;
            }
<link href="~/assetsAdmin/vendors/chartjs/Chart.css" rel="stylesheet" />
<div class="page-heading">
    <div class="page-title">
        <div class="row">
            <div class="col-12 col-md-6 order-md-1 order-last">
                <h3>Báo cáo thống kê doanh thu theo ngày, tháng</h3>
            </div>
            <form asp-controller="StatiscalInvoices" asp-action="Index" method="get">
                <h3>Lựa chọn doanh thu theo ngày, tháng:</h3>
                Từ ngày: <input type="date" id="birthdaytime" name="fromDate" style="
                                                                    border: 1px solid;
                                                                    border-radius: 7px;
                                                                    padding: 8px;
                                                                ">
                đến ngày: <input type="date" id="birthdaytime" name="toDate" style="
                                    border: 1px solid;
                                    border-radius: 7px;
                                    padding: 8px;
                                ">
                <input type="submit" value="Lọc" style="
                                                                    border: 1px solid #2665f2;
                                                                    border-radius: 7px;
                                                                    padding: 10px;
                                                                    background: #1984ff;
                                                                    color: #fff;
                                                                ">
            </form>
        </div>
    </div>
    <section class="section">
        <div class="page-content">
            <section class="row">
                <div class="col-12 col-lg-12">
                    <div class="row">
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body" style="padding-bottom:3.7rem">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng hoá đơn</h6>
                                            <h6 class="font-extrabold mb-0" style="color: #ff0202; font-size: 20px">@ViewBag.countInvoices</h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body px-3 py-4-5">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng hoá đơn chưa duyệt</h6>
                                            <h6 class="font-extrabold mb-0" style="color: #ff0202; font-size: 20px"> @ViewBag.countUnApprove </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body px-3 py-4-5">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng hoá đơn đã duyệt</h6>
                                            <h6 class="font-extrabold mb-0" style="color: #ff0202; font-size: 20px"> @ViewBag.countApproved </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body px-3 py-4-5">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng hoá đơn đang giao</h6>
                                            <h6 class="font-extrabold mb-0" style="color: #ff0202; font-size: 20px"> @ViewBag.countShip </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body px-3 py-4-5">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng hoá đơn đã huỷ</h6>
                                            <h6 class="font-extrabold mb-0" style="color:#ff0202;font-size:20px"> @ViewBag.countCancel </h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-4">
                            <div class="card">
                                <div class="card-body" style="padding-bottom:2.6rem">
                                    <div class="row">
                                        <div class="col-md-8">
                                            <h6 class="text-muted font-semibold">Tổng số doanh thu</h6>
                                                <h6 class="font-extrabold mb-0" style="color: #fad900; font-size: 20px">@doanhThu.ToString("###,0 đ")</h6>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>

            </section>
        </div>
    </section>
</div>