DA_TOTNGHIEP/Areas/Admin/Controllers/ProductTypesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DA_TOTNGHIEP.Models;
using static DA_TOTNGHIEP.Helper;
using DA_TOTNGHIEP.Data;
using Microsoft.AspNetCore.Authorization;

namespace DA_TOTNGHIEP.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Sale")]

    public class ProductTypesController : Controller
    {
        private readonly DA_TOTNGHIEP2Context _context;
        public ProductTypesController(DA_TOTNGHIEP2Context context)
        {
            _context = context;
        }
        
        // GET: Admin/ProductTypes
        public async Task<IActionResult> Index()
        {
            ViewBag.CountStock = _context.Products.Sum(p => p.Stock).ToString("##,#0");
            ViewBag.CountProduct = (from ok in _context.Products select ok.Id).Count().ToString("##,#0");
            ViewBag.TongDoanhThu = _context.Invoices.Where(inv => inv.StatusId == 4).Sum(inv => inv.Total).ToString("##,#0 ₫");
            ViewBag.SoLuongDaBan = _context.InvoiceDetails.Where(inv => inv.MomoConfirm != "Giao dịch Momo bị huỷ" && inv.Invoice.StatusId == 4).Sum(inv => inv.Quantity).ToString("##,#0");

            return View(await _context.ProductTypes.ToListAsync());
        }
        
        [NoDirectAccess]
        public async Task<IActionResult> Create(int id = 0)
        {
            if (id == 0)
                return View(new ProductTypes());

            else
            {
                var productTypes = await _context.ProductTypes.FindAsync(id);
                if (productTypes == null)
                {
                    return NotFound();
                }

                return View(productTypes);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(int id, [Bind("Id,Name,Color,Status,CreatedAt")] ProductTypes productTypes)
        {
            if (ModelState.IsValid)
            {
                //Insert
                if (id == 0)
                {
                    _context.Add(productTypes);
                    await _context.SaveChangesAsync();
                }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.ProductTypes.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Create", productTypes) });
        }

        [NoDirectAccess]
        public async Task<IActionResult> Edit(int id = 0)
        {
            if (id == 0)
                return View(new ProductTypes());
            else
            {
                var productTypes = await _context.ProductTypes.FindAsync(id);
                if (productTypes == null)
                {
                    return NotFound();
                }
                return View(productTypes);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Color,Status,CreatedAt")] ProductTypes productTypes)
        {
                //Update
                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(productTypes);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!ProductTypesExists(productTypes.Id))
                        { return NotFound(); }
                        else
                        { throw; }
                    }
                return Json(new { isValid = true, html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.ProductTypes.ToList()) });
            }
            return Json(new { isValid = false, html = Helper.RenderRazorViewToString(this, "Edit", productTypes) });
        }

        // GET: Admin/ProductTypes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productTypes = await _context.ProductTypes
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productTypes == null)
            {
                return NotFound();
            }

            return View(productTypes);
        }

        // POST: Admin/ProductTypes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var productTypes = await _context.ProductTypes.FindAsync(id);
            _context.ProductTypes.Remove(productTypes);
            await _context.SaveChangesAsync();
            return Json(new { html = Helper.RenderRazorViewToString(this, "_ViewAll", _context.ProductTypes.ToList()) });
        }

        private bool ProductTypesExists(int id)
        {
            return _context.ProductTypes.Any(e => e.Id == id);
        }
    }
}

DA_TOTNGHIEP/Areas/Admin/Views/ProductTypes/Create.cshtml
@model DA_TOTNGHIEP.Models.ProductTypes
@{
    ViewData["Title"] = "Edit";
    Layout = null;
}
<h4>Tạo loại sản phẩm</h4>
<hr />
    <div class="row">
        <form asp-action="Create" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>*@
            <div class="form-group form-check ml-2">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>*@
            <div class="form-group" style="text-align:center">
                <input type="submit" value="Tạo mới" class="btn btn-primary" />
            </div>
        </form>
    </div>

DA_TOTNGHIEP/Areas/Admin/Views/ProductTypes/Details.cshtml
@model DA_TOTNGHIEP.Models.ProductTypes

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>ProductTypes</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Color)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Color)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DA_TOTNGHIEP/Areas/Admin/Views/ProductTypes/Edit.cshtml
@model DA_TOTNGHIEP.Models.ProductTypes
@{
    ViewData["Title"] = "Edit";
    Layout = null;
}
<h4>Sửa loại sản phẩm</h4>
<hr />
    <div class="row">
        <form asp-action="Edit" asp-route-id="@Model.Id" onsubmit="return jQueryAjaxPost(this);">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            @*<div class="form-group">
                <label asp-for="Color" class="control-label"></label>
                <input asp-for="Color" class="form-control" />
                <span asp-validation-for="Color" class="text-danger"></span>
            </div>*@
            <div class="form-group form-check ml-2">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Status" /> @Html.DisplayNameFor(model => model.Status)
                </label>
            </div>
            @*<div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" />
                <span asp-validation-for="CreatedAt" class="text-danger"></span>
            </div>*@
            <div class="form-group" style="text-align:center">
                <input type="submit" value="Sửa" class="btn btn-primary" />
            </div>
        </form>
    </div>

DA_TOTNGHIEP/Areas/Admin/Views/ProductTypes/Index.cshtml
@model IEnumerable<DA_TOTNGHIEP.Models.ProductTypes>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<div id="view-all">
    @await Html.PartialAsync("_ViewAll", Model)

</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DA_TOTNGHIEP/Areas/Admin/Views/ProductTypes/_ViewAll.cshtml
@model IEnumerable<DA_TOTNGHIEP.Models.ProductTypes>

@{
    ViewData["Title"] = "ViewAll";
}
<canvas id="barChart" width="400" height="100"></canvas>

<script>
    var c = document.getElementById("barChart");
    var ctx = c.getContext("2d");
    var tData = $.getValues("/ProductTypes/BarChartDataEF");
    var myBarChart = new Chart(ctx, {
        type: 'bar',
        data: tData
    });
</script>

<h3>Danh sách loại sản phẩm</h3>
<div class="card mt-2">
    <div class="card-content">
        <div class="card-body">
            <a onclick="showInPopup('@Url.Action("Create","ProductTypes",null,Context.Request.Scheme)','Tạo loại sản phẩm')" class="btn btn-primary"><i class='bx bx-plus-circle ml-1'></i><h5 style="display:inline;color:white"> Tạo loại sản phẩm</h5></a>
            <div class="scrollmenu" style="overflow: auto; white-space: nowrap;">
                <div class="table-responsive">
                    <table class="table table-hover mb-0">
                        <thead style="color:#000">
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.Name)
                                </th>
                                @*<th>
                                    @Html.DisplayNameFor(model => model.Color)
                                </th>*@
                                <th>
                                    @Html.DisplayNameFor(model => model.CreatedAt)
                                </th>
                                <th>
                                    @Html.DisplayNameFor(model => model.Status)
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Count() != 0)
                            {
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Name</td>
                                        @*<td>@item.Color</td>*@
                                        <td>@item.CreatedAt</td>
                                        @if (item.Status == true)
                                        {
                                            <td><span class="badge bg-success">Active</span></td>
                                        }
                                        else
                                        {
                                            <td><span class="badge bg-danger">UnActive</span></td>
                                        }
                                        <td>
                                            <div>
                                                <button style="border: none; background: none;" onclick="showInPopup('@Url.Action("Edit","ProductTypes",new {id=item.Id})','Update')"><i title="Sửa" class="fas fa-edit" style="font-size: 23px; color: #415ebf "></i></button>
                                                <form asp-action="Delete" asp-route-id="@item.Id" onsubmit="return jQueryAjaxDelete(this)" class="d-inline">
                                                    <button type="submit" title="Xóa" style="border: none; background: none;"><i class="fas fa-trash-alt" style="font-size:23px;color:crimson"></i></button>
                                                </form>
                                            </div>
                                        </td>
                                    </tr>
                                }

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>